version: "3.9"

services:
  # livekit:
  #   image: livekit/livekit-server:v1.3
  #   command: 
  #     - "--config=/etc/livekit.yaml"
  #     - "--node-ip=144.202.109.163"
  #   # network_mode: "host"
  #   # expose:
  #   #   - "80"
  #   #   - "443"
  #   ports:
  #     - '7880/tcp'
  #     - '7881/tcp'
  #     # - '5349:5349/tcp'
  #     # - '5349:5349/udp'
  #     # - "50000-60000:50000-60000/udp"
  #     - "50000-50100:50000-50100/udp"
  #   volumes:
  #     - ./configs/livekit.yaml:/etc/livekit.yaml
  #   restart: unless-stopped

  weloveparty_free_map_service:
    build: 
      context: ../java_free_map_backend_system
      dockerfile: ./Dockerfile
    image: yingshaoxo/weloveparty_free_map_backend_service
    expose:
      - "40055"
    # ports:
    #   - "40055:40055"
    # volumes:
    #   - type: bind
    #     source: ./configs/python_chat_with_friends_system/config.py
    #     target: /code/src/config.py
    environment: 
      - redis_network_name=redis
      - postgres_sql_host=db
      - postgres_sql_user=yingshaoxo
      - postgres_sql_password=yingshaoxo
    restart: unless-stopped
