version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=yingshaoxo
      - POSTGRES_PASSWORD=yingshaoxo
    # expose:
    #   - "5432:5432"
    ports:
      - '5432:5432'
    volumes: 
      - ./configs/postgre_sql_db:/var/lib/postgresql/data