version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:v1.3
    command: 
      - "--config=/etc/livekit.yaml"
      - "--node-ip=144.202.109.163"
    # network_mode: "host"
    # expose:
    #   - "80"
    #   - "443"
    ports:
      - '7880/tcp'
      - '7881/tcp'
      # - '5349:5349/tcp'
      # - '5349:5349/udp'
      # - "50000-60000:50000-60000/udp"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./configs/livekit.yaml:/etc/livekit.yaml
    restart: unless-stopped

