version: "3.9"
services:
  # caddy:
  #   #image: livekit/caddyl4
  #   build:
  #     context: ./
  #     dockerfile: ./caddyl4_Dockerfile
  #   #command: run --config /etc/caddy.yaml --adapter yaml
  #   command: run --config /etc/caddy.json
  #   restart: unless-stopped
  #   network_mode: "host"
  #   volumes:
  #     #- ./caddy.yaml:/etc/caddy.yaml
  #     - ./caddy.json:/etc/caddy.json
  #     - ./caddy_data:/data

  # www:
  #     image: aikain/simplehttpserver:0.1
  #     #network_mode: "host"
  #     ports:
  #       - "8082:80"
  #     volumes:
  #       - "./:/var/www"
  #     restart: always

  # redis:
  #   image: redis:6-alpine
  #   command: redis-server /etc/redis.conf
  #   network_mode: "host"
  #   # ports:
  #   #   - '6379:6379'
  #     # - "1-65535:1-65535"
  #   volumes:
  #     - ./configs/redis.conf:/etc/redis.conf  
  #     - ./configs/redis_data:/data
  #   restart: unless-stopped

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    #network_mode: "host"
    ports:
      - '6379:6379'
    environment:
      - bind=127.0.0.1
    restart: unless-stopped

  # livekit:
  #   image: livekit/livekit-server:latest
  #   command: --config /etc/livekit.yaml
  #   network_mode: "host"
  #   ports:
  #     - '7880'
  #     - '7881'
  #     - '5349'
  #     - "443:443/udp"
  #     #- "50000-60000:50000-60000"
  #   volumes:
  #     - ./configs/livekit.yaml:/etc/livekit.yaml
  #   restart: unless-stopped