## in /etc/hosts
# 127.0.0.1 weloveparty.domain.local auth.weloveparty.domain.local whoami.weloveparty.domain.local internal_api.weloveparty.domain.local account_storage.weloveparty.domain.local livekit.weloveparty.domain.local livekit_turn.weloveparty.domain.local 


http:
  routers:
    whoami_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`whoami.weloveparty.domain.local`)"
      service: whoami_service
    grpc_auth_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`auth.weloveparty.domain.local`)"
      # rule: PathPrefix(`/auth`) 
      middlewares:
        - test-grpcweb
        # - test-stripprefix
      service: weloveparty_account_auth_service
    grpc_internal_api_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`internal_api.weloveparty.domain.local`)"
      # middlewares:
      #   - my_jwt_auth
      service: weloveparty_internal_api_service
    grpc_account_storage_service_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`account_storage.weloveparty.domain.local`)"
      middlewares:
        - my_jwt_auth
      service: weloveparty_account_storage_service
    grpc_room_control_service_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`room_control.weloveparty.domain.local`)"
      middlewares:
        - my_jwt_auth
      service: weloveparty_room_control_service
    livekit:
      entryPoints:
        - web
        - websecure
      rule: "Host(`livekit.weloveparty.domain.local`)"
      service: livekit_service

  middlewares:
    test-stripprefix:
      stripPrefix:
        prefixes:
          - "/auth"
    my_jwt_auth:
        forwardAuth:
          address: "http://weloveparty_account_auth_service:40051/v1/jwt_auth_gateway/"
          # address: "http://host.docker.internal:40051/v1/jwt_auth_gateway/"
          authResponseHeaders:
              - "user_email" # jwt_auth_gateway will put this header to the original request
    test-grpcweb:
      grpcWeb:
        allowOrigins:
          - "*"

  services:
    whoami_service:
      loadBalancer:
        servers:
          - url: http://whoami:80
    weloveparty_account_auth_service:
      loadBalancer:
        servers:
          - url: h2c://weloveparty_account_auth_service:40052
          #- url: h2c://host.docker.internal:40052
        passHostHeader: true
    weloveparty_internal_api_service:
      loadBalancer:
        servers:
          # - url: h2c://weloveparty_internal_api_service:40050
          - url: h2c://host.docker.internal:40050
        passHostHeader: true
    weloveparty_account_storage_service:
      loadBalancer:
        servers:
          # - url: h2c://weloveparty_account_storage_service:40053
          - url: h2c://host.docker.internal:40053
        passHostHeader: true
    weloveparty_room_control_service:
      loadBalancer:
        servers:
          - url: h2c://weloveparty_room_control_service:40054
          # - url: h2c://host.docker.internal:40054
        passHostHeader: true
    livekit_service:
      loadBalancer:
        servers:
          - url: http://livekit:7880
        passHostHeader: true