http:
  routers:
    grpc_auth_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`auth.weloveparty.domain.local`)"
      # rule: PathPrefix(`/auth`) 
      middlewares:
        # - test-stripprefix
      service: weloveparty_account_auth_service
    grpc_internal_api_router:
      entryPoints:
        - web
        - websecure
      rule: "Host(`internal_api.weloveparty.domain.local`)"
      # middlewares:
      #   - my_jwt_auth
      service: weloveparty_internal_api_service

  middlewares:
    test-stripprefix:
      stripPrefix:
        prefixes:
          - "/auth"
    my_jwt_auth:
        forwardAuth:
          # address: "http://weloveparty_account_auth_service:40051/v1/jwt_auth_gateway/"
          address: "http://host.docker.internal:40051/v1/jwt_auth_gateway/"
          authResponseHeaders:
              - "user_email" # jwt_auth_gateway will put this header to the original request

  services:
    weloveparty_internal_api_service:
      loadBalancer:
        servers:
          - url: h2c://weloveparty_internal_api_service:40050
          # - url: h2c://host.docker.internal:40050
        passHostHeader: true
    weloveparty_account_auth_service:
      loadBalancer:
        servers:
          - url: h2c://weloveparty_account_auth_service:40052
          #- url: h2c://host.docker.internal:40052
        passHostHeader: true